### PR TITLE
added new esri tools to generator

### PR DESCRIPTION
**Pull request by thorsten-reitz**
@alexanderkotsev I had to add the new files to the generator. Local output looks good, please check & confirm.

### CODE REVIEW

**Comment by alexanderkotsev** [comment]
Hi Thorsten,
I still get the geojson and gml tests mixed. See the attached snapshot for reference. 

2019-06-28-203807_2560x1335_scrot

**Comment by thorsten-reitz** [comment]
You are right. And it*s quite interesting because the order changes from run to run. Will investigate now.

**Comment by alexanderkotsev** [comment]
Any news on this issue? It would be nice to have it ready for Monday. If not possible, I can temporarily rearrange the test results?

**Comment by thorsten-reitz** [comment]
@alexanderkotsev please merge this fix for the data file, I have an additional fix for the generator on a separate PR.

**Pull request merged**
